### PR TITLE
Image

### PR DESCRIPTION
**Pull request by nikhiljugale007**
Raised PR for image component:

### CODE REVIEW

**Review by amarphule — CHANGES_REQUESTED** [review]
It would be better if you provide various sizes of the round images like small, medium, large. Other than that you have done a fantastic job very good.

**Comment by nikhiljugale007** [comment]
> It would be better if you provide various sizes of the round images like small, medium, large. Other than that you have done a fantastic job very good.

I have given different sizes in the avatar component. img-round class is used only for making images round no matter what their size.

**Comment by Naman-Saxena1** [comment]
I believe for responsive image srcset should be used to provide multiple images with size attribute to the browser.

**Comment by nikhiljugale007** [comment]
> I believe for responsive image srcset should be used to provide multiple images with size attribute to the browser.

I will try this.

**Pull request merged**
