### PR TITLE
Card

### PR DESCRIPTION
**Pull request by nikhiljugale007**
Review PR for Card Component

PREVIEW: https://vercel-ui-preview.netlify.app/component-lib/cards.html

### CODE REVIEW

**Comment by Naman-Saxena1** [comment]
Since you have made border: 0, there is no way of knowing if the button is clicked or not. You can either keep border or provide some custom animation on button click. Everything else looks fine.

**Comment by sakleprajwal** [comment]
When I click on any button in mobile phone, it gives an outline which is not a good UX. Use below code for every button:
.btn:focus { outline: none; }

**Comment by sakleprajwal** [comment]
Website is not responsive on mobile phone. Use relative width for containers.

**Review by vijaytembugade — APPROVED** [review]
Border Around each card/component is disturbing. Instead of dark black, you can give that with light shade.

**Comment by nikhiljugale007** [comment]
> Since you have made border: 0, there is no way of knowing if the button is clicked or not. You can either keep border or provide some custom animation on button click. Everything else looks fine.

Added styling for button click. Please check.

**Pull request merged**
