### PR TITLE
added list component

### PR DESCRIPTION
**Pull request by nikhiljugale007**
review list component

PREVIEW:https://vercel-ui-preview.netlify.app/component-lib/list.html

### CODE REVIEW

**Review by Naman-Saxena1 — APPROVED** [review]
I checked code and preview, can't find any major issues, seems good to me 👍

**Comment by prankurpandeyy** [comment]
@Naman-Saxena1 on installation option the actual code is not properly overlapping in container ,rest all code is fine ,

**Comment by nikhiljugale007** [comment]
> 

That is an issue with carbon still trying to fix that.

**Comment by prankurpandeyy** [comment]
you can use highlight js it works like charm, do let me know if you want to integrate this in your projects

**Review by Ankur9669 — COMMENTED** [review]
Did not find any mistakes. looks good to merge. Great Work!!

**Pull request merged**
